language: crystal

script:
 - crystal docs
 - crystal tool format --check
# - crystal spec

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: em
  on:
    branch: master
  local_dir: docs
